### PR TITLE
NDRCN-471-Removed Postcode validation

### PR DESCRIPTION
**Pull request by simms11**

### CODE REVIEW

**Review by lmugnai — COMMENTED** [review]
Hi @simms11 why did you decide to remove this. I think it would be best to keep it but amend the regex.

**Comment by simms11** [comment]
@lmugnai I removed this because as it stands the only validation that we are doing is to ensure that the user inputs a value between 2-10 characters. Which has been done upon the FE.

from a regex stand point, I will change """([a-zA-Z0-9]{6,9})""" to """([a-zA-Z0-9]{2,10})"""

**Comment by lmugnai** [comment]
@simms11 yes we do have similar tests in the frontend to ensure the user inputs a valid value, however, the stubs is doing it's best to mimic what EIS/Pega does, that's why we have this validation in the stubs too. I think we should keep this in and change the regex as you've mentioned.

**Comment by simms11** [comment]
@lmugnai  PR: https://github.com/hmrc/national-duty-repayment-center-stubs/pull/14

**Pull request closed without merging**
